import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  WidthType,
  Footer,
  PageNumber,
} from "docx"
import { FormattedDocument } from "./formatter"

export async function generateDocx(doc: FormattedDocument): Promise<Buffer> {
  const children: (Paragraph | Table)[] = []

  // Document Title
  children.push(
    new Paragraph({
      text: doc.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.LEFT,
      spacing: { after: 120 },
    })
  )

  // Document Metadata Block
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: "Subject: ", bold: true }),
        new TextRun({ text: doc.subject + "   |   " }),
        new TextRun({ text: "Date: ", bold: true }),
        new TextRun({ text: doc.date + "   |   " }),
        new TextRun({ text: "Generated By: ", bold: true }),
        new TextRun({ text: doc.author, italic: true }),
      ],
      spacing: { after: 300 },
    })
  )

  // Table of Contents
  if (doc.toc.length > 1) {
    children.push(
      new Paragraph({
        text: "Table of Contents",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 120 },
      })
    )

    doc.toc.forEach((heading, idx) => {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${idx + 1}. `, bold: true }),
            new TextRun({ text: heading }),
          ],
          spacing: { after: 60 },
        })
      )
    })

    children.push(
      new Paragraph({
        text: "───────────────────────────────────────────────────",
        alignment: AlignmentType.CENTER,
        spacing: { before: 200, after: 300 },
      })
    )
  }

  // Sections
  doc.sections.forEach((section) => {
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 150 },
      })
    )

    if (section.type === "text" && section.content) {
      const paragraphs = section.content.split("\n\n")
      paragraphs.forEach((pText) => {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: pText.replace(/\n/g, " ") })],
            spacing: { after: 140 },
          })
        )
      })
    }

    if (section.type === "qa" && section.pairs) {
      section.pairs.forEach((pair, idx) => {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `Q${idx + 1}: `, bold: true, color: "0284C7" }),
              new TextRun({ text: pair.q, bold: true }),
            ],
            spacing: { before: 180, after: 80 },
          })
        )

        if (pair.time) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({ text: `Asked at ${pair.time}`, italic: true, size: 18, color: "64748B" }),
              ],
              spacing: { after: 60 },
            })
          )
        }

        const answerParagraphs = pair.a.split("\n\n")
        answerParagraphs.forEach((aText) => {
          children.push(
            new Paragraph({
              children: [
                new TextRun({ text: "Answer: ", bold: true, color: "10B981" }),
                new TextRun({ text: aText.replace(/\n/g, " ") }),
              ],
              spacing: { after: 160 },
            })
          )
        })
      })
    }

    if (section.type === "list" && section.items) {
      section.items.forEach((item) => {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: "• ", bold: true }),
              new TextRun({ text: item }),
            ],
            spacing: { after: 80 },
          })
        )
      })
    }

    if (section.type === "table" && section.headers && section.rows) {
      const tableRows: TableRow[] = []

      // Header Row
      tableRows.push(
        new TableRow({
          children: section.headers.map(
            (header) =>
              new TableCell({
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: header, bold: true, color: "FFFFFF" })],
                  }),
                ],
                shading: { fill: "1E293B" },
                width: { size: Math.floor(100 / section.headers!.length), type: WidthType.PERCENTAGE },
              })
          ),
        })
      )

      // Data Rows
      section.rows.forEach((row, rowIdx) => {
        tableRows.push(
          new TableRow({
            children: row.map(
              (cell) =>
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [new TextRun({ text: cell })],
                    }),
                  ],
                  shading: { fill: rowIdx % 2 === 0 ? "F8FAFC" : "FFFFFF" },
                  width: { size: Math.floor(100 / row.length), type: WidthType.PERCENTAGE },
                })
            ),
          })
        )
      })

      children.push(
        new Table({
          rows: tableRows,
          width: { size: 100, type: WidthType.PERCENTAGE },
        })
      )

      children.push(
        new Paragraph({ text: "", spacing: { after: 200 } })
      )
    }
  })

  // Create DOCX document with footer
  const wordDoc = new Document({
    sections: [
      {
        properties: {},
        children,
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: doc.footer + "   |   Page " }),
                  new TextRun({ children: [PageNumber.CURRENT] }),
                ],
              }),
            ],
          }),
        },
      },
    ],
  })

  return await Packer.toBuffer(wordDoc)
}
