import { FormattedDocument } from "./formatter"

export function generateMarkdown(doc: FormattedDocument): string {
  const lines: string[] = []

  // Document Title & Metadata
  lines.push(`# ${doc.title}`)
  lines.push(`**Subject:** ${doc.subject}`)
  lines.push(`**Date:** ${doc.date}`)
  lines.push(`**Generated By:** ${doc.author}`)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Table of Contents
  if (doc.toc.length > 1) {
    lines.push("## Table of Contents")
    doc.toc.forEach((heading, idx) => {
      const slug = heading.toLowerCase().replace(/[^a-z0-9]+/g, "-")
      lines.push(`${idx + 1}. [${heading}](#${slug})`)
    })
    lines.push("")
    lines.push("---")
    lines.push("")
  }

  // Sections
  doc.sections.forEach((section) => {
    lines.push(`## ${section.title}`)
    lines.push("")

    if (section.type === "text" && section.content) {
      lines.push(section.content)
      lines.push("")
    }

    if (section.type === "qa" && section.pairs) {
      section.pairs.forEach((pair, idx) => {
        lines.push(`### ${idx + 1}. ${pair.q}`)
        if (pair.time) {
          lines.push(`*Asked at ${pair.time}*`)
        }
        lines.push("")
        lines.push(pair.a)
        lines.push("")
      })
    }

    if (section.type === "list" && section.items) {
      section.items.forEach((item) => {
        lines.push(`- ${item}`)
      })
      lines.push("")
    }

    if (section.type === "table" && section.headers && section.rows) {
      // Header row
      lines.push(`| ${section.headers.join(" | ")} |`)
      // Separator row
      lines.push(`| ${section.headers.map(() => "---").join(" | ")} |`)
      // Data rows
      section.rows.forEach((row) => {
        const cleanRow = row.map((cell) => cell.replace(/\n/g, " "))
        lines.push(`| ${cleanRow.join(" | ")} |`)
      })
      lines.push("")
    }

    lines.push("")
  })

  // Footer
  lines.push("---")
  lines.push(`*${doc.footer}*`)

  return lines.join("\n")
}
