import PDFDocument from "pdfkit"
import { FormattedDocument } from "./formatter"

export async function generatePdf(doc: FormattedDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const pdf = new PDFDocument({ margin: 50, bufferPages: true })
      const buffers: Buffer[] = []

      pdf.on("data", (chunk: Buffer) => buffers.push(chunk))
      pdf.on("end", () => resolve(Buffer.concat(buffers)))
      pdf.on("error", (err: Error) => reject(err))

      // Header Title
      pdf.fontSize(22).fillColor("#0f172a").text(doc.title, { align: "left" })
      pdf.moveDown(0.5)

      // Metadata Box
      pdf.fontSize(10).fillColor("#475569").text(`Subject: ${doc.subject}  |  Date: ${doc.date}`)
      pdf.fontSize(10).fillColor("#64748b").text(`Generated By: ${doc.author}`)
      pdf.moveDown(0.8)
      pdf.strokeColor("#cbd5e1").lineWidth(1).moveTo(50, pdf.y).lineTo(545, pdf.y).stroke()
      pdf.moveDown(0.8)

      // Table of contents if > 1 section
      if (doc.toc.length > 1) {
        pdf.fontSize(14).fillColor("#1e293b").text("Table of Contents")
        pdf.moveDown(0.4)
        doc.toc.forEach((item, i) => {
          pdf.fontSize(10).fillColor("#0284c7").text(`${i + 1}. ${item}`)
        })
        pdf.moveDown(0.8)
        pdf.strokeColor("#e2e8f0").lineWidth(0.5).moveTo(50, pdf.y).lineTo(545, pdf.y).stroke()
        pdf.moveDown(0.8)
      }

      // Sections
      doc.sections.forEach((section) => {
        if (pdf.y > 680) {
          pdf.addPage()
        }

        pdf.fontSize(15).fillColor("#0f172a").text(section.title)
        pdf.moveDown(0.5)

        if (section.type === "text" && section.content) {
          pdf.fontSize(10).fillColor("#334155").text(section.content, { lineGap: 3 })
          pdf.moveDown(1)
        }

        if (section.type === "qa" && section.pairs) {
          section.pairs.forEach((pair, idx) => {
            if (pdf.y > 650) pdf.addPage()

            pdf.fontSize(11).fillColor("#0284c7").text(`Q${idx + 1}: ${pair.q}`)
            if (pair.time) {
              pdf.fontSize(8).fillColor("#94a3b8").text(`Asked at ${pair.time}`)
            }
            pdf.moveDown(0.3)
            pdf.fontSize(10).fillColor("#1e293b").text(`Answer:\n${pair.a}`, { lineGap: 3 })
            pdf.moveDown(0.8)
          })
        }

        if (section.type === "list" && section.items) {
          section.items.forEach((item) => {
            if (pdf.y > 700) pdf.addPage()
            pdf.fontSize(10).fillColor("#334155").text(`• ${item}`)
          })
          pdf.moveDown(0.8)
        }

        if (section.type === "table" && section.headers && section.rows) {
          section.rows.forEach((row, rIdx) => {
            if (pdf.y > 660) pdf.addPage()
            const rowText = row
              .map((cell, cIdx) => `• ${section.headers![cIdx] || "Field"}: ${cell}`)
              .join("\n")
            pdf.fontSize(9).fillColor("#334155").text(`Card / Item ${rIdx + 1}:\n${rowText}`)
            pdf.moveDown(0.6)
          })
          pdf.moveDown(0.8)
        }
      })

      // Footers with page numbers
      const range = pdf.bufferedPageRange()
      for (let i = range.start; i < range.start + range.count; i++) {
        pdf.switchToPage(i)
        pdf.fontSize(9).fillColor("#64748b").text(
          `${doc.footer} | Page ${i + 1} of ${range.count}`,
          50,
          750,
          { align: "center" }
        )
      }

      pdf.end()
    } catch (err) {
      reject(err)
    }
  })
}
